library(groupdata2)
context("collapse_groups()")

test_that("numerical balancing works with collapse_groups()", {

  # Create data frame
  xpectr::set_test_seed(42)
  df <- data.frame(
    "participant" = factor(rep(1:20, 3)),
    "age" = rep(sample(c(1:100), 20), 3),
    "diagnosis" = factor(rep(sample(c("a", "b"), 20, replace = T), 3)),
    "score" = sample(c(1:100), 20 * 3)
  )
  df <- df %>% dplyr::arrange(participant)
  df$session <- rep(c("1", "2", "3"), 20)

  df_folded <- fold(data = df, k = 8, method = "n_dist", id_col = "participant")

  pre_mean_age <- df_folded %>%
    dplyr::summarise(mean_age = mean(age))

  ## Testing 'pre_mean_age'                                                 ####
  ## Initially generated by xpectr
  # Testing column values
  expect_equal(
    pre_mean_age[[".folds"]],
    structure(1:8, .Label = c("1", "2", "3", "4", "5", "6", "7", "8"),
      class = "factor"))
  expect_equal(
    pre_mean_age[["mean_age"]],
    c(37.5, 67.33333, 63.5, 48, 56, 76.66667, 61.5, 48.33333),
    tolerance = 1e-4)

  df_collapsed <-
    collapse_groups(
      dplyr::ungroup(df_folded),
      n = 4,
      group_cols = ".folds",
      num_col = "age",
      num_method = "balance",
      group_aggregation_fn = mean
    )

  post_mean_age <- df_collapsed %>%
    dplyr::summarise(mean_age = mean(age))


  ## Testing 'post_mean_age'                                                ####
  ## Initially generated by xpectr
  # Testing column values
  expect_equal(
    post_mean_age[[".coll_groups"]],
    structure(1:4, .Label = c("1", "2", "3", "4"), class = "factor"))
  expect_equal(
    post_mean_age[["mean_age"]],
    c(57.66667, 61, 58.75, 54.4),
    tolerance = 1e-4)

  df_collapsed <-
    collapse_groups(
      dplyr::ungroup(df_folded),
      n = 4,
      group_cols = ".folds",
      num_col = "age",
      num_method = "descending",
      group_aggregation_fn = mean
    )

  post_mean_age <- df_collapsed %>%
    dplyr::summarise(mean_age = mean(age))

  ## Testing 'post_mean_age'                                                ####
  ## Initially generated by xpectr
  # Testing column values
  expect_equal(
    post_mean_age[[".coll_groups"]],
    structure(1:4, .Label = c("1", "2", "3", "4"), class = "factor"))
  expect_equal(
    post_mean_age[["mean_age"]],
    c(72, 62.5, 51.4, 43.8),
    tolerance = 1e-4)

  df_collapsed <-
    collapse_groups(
      dplyr::ungroup(df_folded),
      n = 4,
      group_cols = ".folds",
      num_col = "age",
      num_method = "ascending",
      group_aggregation_fn = mean
    )

  post_mean_age <- df_collapsed %>%
    dplyr::summarise(mean_age = mean(age))


  ## Testing 'post_mean_age'                                                ####
  ## Initially generated by xpectr
  # Testing column values
  expect_equal(
    post_mean_age[[".coll_groups"]],
    structure(1:4, .Label = c("1", "2", "3", "4"), class = "factor"))
  expect_equal(
    post_mean_age[["mean_age"]],
    c(43.8, 51.4, 62.5, 72),
    tolerance = 1e-4)


  #### CAT COL DEV ####

  df_collapsed <-
    collapse_groups(
      dplyr::ungroup(df_folded),
      n = 4,
      group_cols = ".folds",
      cat_col = "age",
      cat_method = "balance",
      cat_selection_method = "majority"
    )

})
