library(groupdata2)
context("collapse_groups()")

test_that("numerical balancing works with collapse_groups()", {

  # Create data frame
  xpectr::set_test_seed(42)
  df <- data.frame(
    "participant" = factor(rep(1:20, 3)),
    "age" = rep(sample(c(1:100), 20), 3),
    "diagnosis" = factor(rep(sample(c("a", "b"), 20, replace = T), 3)),
    "score" = sample(c(1:100), 20 * 3)
  )
  df <- df %>% dplyr::arrange(participant)
  df$session <- rep(c("1", "2", "3"), 20)

  df_folded <- fold(data = df, k = 8, method = "n_dist", id_col = "participant")

  pre_mean_age <- df_folded %>%
    dplyr::summarise(mean_age = mean(age))

  ## Testing 'pre_mean_age'                                                 ####
  ## Initially generated by xpectr
  # Testing column values
  expect_equal(
    pre_mean_age[[".folds"]],
    structure(1:8, .Label = c("1", "2", "3", "4", "5", "6", "7", "8"),
      class = "factor"))
  expect_equal(
    pre_mean_age[["mean_age"]],
    c(37.5, 67.33333, 63.5, 48, 56, 76.66667, 61.5, 48.33333),
    tolerance = 1e-4)

  df_collapsed <-
    collapse_groups(
      dplyr::ungroup(df_folded),
      n = 4,
      group_cols = ".folds",
      num_col = "age",
      num_method = "balance",
      group_aggregation_fn = mean
    )

  post_mean_age <- df_collapsed %>%
    dplyr::summarise(mean_age = mean(age))


  ## Testing 'post_mean_age'                                                ####
  ## Initially generated by xpectr
  # Testing column values
  expect_equal(
    post_mean_age[[".coll_groups"]],
    structure(1:4, .Label = c("1", "2", "3", "4"), class = "factor"))
  expect_equal(
    post_mean_age[["mean_age"]],
    c(57.66667, 61, 58.75, 54.4),
    tolerance = 1e-4)

  df_collapsed <-
    collapse_groups(
      dplyr::ungroup(df_folded),
      n = 4,
      group_cols = ".folds",
      num_col = "age",
      num_method = "descending",
      group_aggregation_fn = mean
    )

  post_mean_age <- df_collapsed %>%
    dplyr::summarise(mean_age = mean(age))

  ## Testing 'post_mean_age'                                                ####
  ## Initially generated by xpectr
  # Testing column values
  expect_equal(
    post_mean_age[[".coll_groups"]],
    structure(1:4, .Label = c("1", "2", "3", "4"), class = "factor"))
  expect_equal(
    post_mean_age[["mean_age"]],
    c(72, 62.5, 51.4, 43.8),
    tolerance = 1e-4)

  df_collapsed <-
    collapse_groups(
      dplyr::ungroup(df_folded),
      n = 4,
      group_cols = ".folds",
      num_col = "age",
      num_method = "ascending",
      group_aggregation_fn = mean
    )

  post_mean_age <- df_collapsed %>%
    dplyr::summarise(mean_age = mean(age))


  ## Testing 'post_mean_age'                                                ####
  ## Initially generated by xpectr
  # Testing column values
  expect_equal(
    post_mean_age[[".coll_groups"]],
    structure(1:4, .Label = c("1", "2", "3", "4"), class = "factor"))
  expect_equal(
    post_mean_age[["mean_age"]],
    c(43.8, 51.4, 62.5, 72),
    tolerance = 1e-4)


  #### CAT COL DEV ####

  xpectr::set_test_seed(1)
  df_collapsed <- df_folded %>%
    dplyr::ungroup() %>%
    dplyr::sample_frac(size = 0.8) %>%
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      num_col = "age",
      cat_col = "diagnosis",
      cat_levels = ".majority",
      col_name = ".cg1"
    ) %>%
    dplyr::ungroup() %>%
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      num_col = "age",
      cat_col = "diagnosis",
      cat_levels = NULL,
      col_name = ".cg2"
    ) %>%
    dplyr::ungroup() %>%
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      num_col = "age",
      col_name = ".cg3"
    ) %>%
    dplyr::ungroup() %>%
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      cat_col = "diagnosis",
      cat_levels = ".majority",
      col_name = ".cg4"
    ) %>%
    dplyr::ungroup() %>%
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      col_name = ".cg5"
    ) %>%
    dplyr::ungroup()  %>%
    collapse_groups(
      n = 4,
      balance_size = FALSE,
      group_cols = ".folds",
      col_name = ".cg6"
    ) %>%
    dplyr::ungroup()

  score_group_balances(
    df_collapsed,
    group_col = paste0(".cg", 1:6),
    cat_col = "diagnosis",
    num_col = "age"
  )

  # Test for different test script
  # When cat_col levels are already columns?
  df_folded %>% dplyr::mutate(diagnosis2 = factor(ifelse(diagnosis == "a", "size", "group"))) %>%
    summarize_group_balances(".folds", cat_col="diagnosis2", num_col="age", id_col="participant")

})
