library(groupdata2)
context("collapse_groups()")


test_that("unit testing collapse_groups()", {

  # prepare_collapse_groups_run_
  # prepare_collapse_groups_output_
  # run_collapse_groups_
  # replace_forbidden_names_
  # add_new_groups_
  # calculate_summary
  # create_combined_cat_summary_
  # scale_combine_cols_
  # combine_scaled_cols_
  # add_ordered_summary_groups_

  #### List arguments ####
  # TODO Test .minority/.majority on its own and within list

  #### Summarization ####

  #### Combination ####

  #### Auto-tune ####



})





test_that("numerical balancing works with collapse_groups()", {

  # Create data frame
  xpectr::set_test_seed(42)
  df <- data.frame(
    "participant" = factor(rep(1:20, 3)),
    "age" = rep(sample(c(1:100), 20), 3),
    "diagnosis" = factor(rep(sample(c("a", "b"), 20, replace = T), 3)),
    "score" = sample(c(1:100), 20 * 3)
  )
  df <- df %>% dplyr::arrange(participant)
  df$session <- rep(c("1", "2", "3"), 20)

  df_folded <- fold(data = df, k = 8, method = "n_dist", id_col = "participant")

  pre_mean_age <- df_folded %>%
    dplyr::summarise(mean_age = mean(age))

  ## Testing 'pre_mean_age'                                                 ####
  ## Initially generated by xpectr
  # Testing column values
  expect_equal(
    pre_mean_age[[".folds"]],
    structure(1:8, .Label = c("1", "2", "3", "4", "5", "6", "7", "8"),
      class = "factor"))
  expect_equal(
    pre_mean_age[["mean_age"]],
    c(37.5, 67.33333, 63.5, 48, 56, 76.66667, 61.5, 48.33333),
    tolerance = 1e-4)

  xpectr::set_test_seed(42)
  df_collapsed <-
    collapse_groups(
      dplyr::ungroup(df_folded),
      n = 4,
      group_cols = ".folds",
      num_cols = "age",
      group_aggregation_fn = mean
    )

  post_mean_age <- df_collapsed %>%
    dplyr::group_by(.coll_groups) %>%
    dplyr::summarise(mean_age = mean(age))


  ## Testing 'post_mean_age'                                                ####
  ## Initially generated by xpectr
  # Testing column values
  expect_equal(
    post_mean_age[[".coll_groups"]],
    structure(1:4, .Label = c("1", "2", "3", "4"), class = "factor"))
  expect_equal(
    post_mean_age[["mean_age"]],
    c(53.6, 54.2, 61, 62.8),
    tolerance = 1e-4)

  xpectr::set_test_seed(42)
  df_collapsed <-
    collapse_groups(
      dplyr::ungroup(df_folded),
      n = 4,
      group_cols = ".folds",
      num_cols = "age",
      balance_size = FALSE,
      method = "descending",
      group_aggregation_fn = mean
    )

  post_mean_age <- df_collapsed %>%
    dplyr::group_by(.coll_groups) %>%
    dplyr::summarise(mean_age = mean(age))

  ## Testing 'post_mean_age'                                                ####
  ## Initially generated by xpectr
  # Testing column values
  expect_equal(
    post_mean_age[[".coll_groups"]],
    structure(1:4, .Label = c("1", "2", "3", "4"), class = "factor"))
  expect_equal(
    post_mean_age[["mean_age"]],
    c(72, 62.5, 51.4, 43.8),
    tolerance = 1e-4)

  df_collapsed <-
    collapse_groups(
      dplyr::ungroup(df_folded),
      n = 4,
      group_cols = ".folds",
      num_col = "age",
      method = "ascending",
      group_aggregation_fn = mean
    )

  post_mean_age <- df_collapsed %>%
    dplyr::summarise(mean_age = mean(age))


  ## Testing 'post_mean_age'                                                ####
  ## Initially generated by xpectr
  # Testing column values
  expect_equal(
    post_mean_age[[".coll_groups"]],
    structure(1:4, .Label = c("1", "2", "3", "4"), class = "factor"))
  expect_equal(
    post_mean_age[["mean_age"]],
    c(43.8, 51.4, 62.5, 72),
    tolerance = 1e-4)


  #### CAT COL DEV ####

  xpectr::set_test_seed(1)
  df_collapsed <- df_folded %>%
    dplyr::ungroup() %>%
    dplyr::sample_frac(size = 0.8) %>%
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      num_col = "age",
      cat_col = "diagnosis",
      cat_levels = ".majority",
      col_name = ".cg1"
    ) %>%
    dplyr::ungroup() %>%
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      num_col = "age",
      cat_col = "diagnosis",
      cat_levels = NULL,
      col_name = ".cg2"
    ) %>%
    dplyr::ungroup() %>%
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      num_col = "age",
      col_name = ".cg3"
    ) %>%
    dplyr::ungroup() %>%
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      cat_col = "diagnosis",
      cat_levels = ".majority",
      col_name = ".cg4"
    ) %>%
    dplyr::ungroup() %>%
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      col_name = ".cg5"
    ) %>%
    dplyr::ungroup()  %>%
    collapse_groups(
      n = 4,
      balance_size = FALSE,
      group_cols = ".folds",
      col_name = ".cg6"
    ) %>%
    dplyr::ungroup()

  summarize_balances(
    df_collapsed,
    paste0(".cg", 1:6),
    num_cols = c("age"),
    cat_cols = "diagnosis",
    id_cols = "participant"
  )$Summary %>% dplyr::filter(measure == "SD")

  # Test for different test script
  # When cat_col levels are already columns?
  df_folded %>% dplyr::mutate(diagnosis2 = factor(ifelse(diagnosis == "a", "size", "group"))) %>%
    summarize_group_balances(".folds", cat_col="diagnosis2", num_col="age", id_col="participant")

})


test_that("testing ...()", {

  seed <- 67

  # Create data frame
  xpectr::set_test_seed(seed)
  df <- data.frame(
    "participant" = factor(rep(1:30, 5)),
    "score" = sample(c(1:100), 150, replace = T),
    "diagnosis" = factor(sample(c("a", "b", "c"), 150, replace = T))
  ) %>% dplyr::arrange(.data$participant) %>%
    dplyr::as_tibble()

  xpectr::set_test_seed(seed)
  df_folded <- fold(data = df, k = 13, method = "n_dist")

  # TODO We must set seed between each collapsing, or we can't compare completely?

  xpectr::set_test_seed(seed)
  df_collapsed <- df_folded %>%
    dplyr::ungroup() %>%
    dplyr::sample_frac(size = 0.8)  %>%
    dplyr::mutate(sampl = factor(sample(1:4, dplyr::n(), replace = TRUE))) %>%
    # No balancing
    # Default settings
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      col_name = "R",
      balance_size = FALSE
    ) %>%
    dplyr::ungroup() %>%
    # All balancings
    # Default settings
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      num_col = "score",
      cat_col = "diagnosis",
      cat_levels = ".majority",
      id_col = "participant",
      balance_size = TRUE,
      col_name = "n,i,s,c^"
    ) %>%
    dplyr::ungroup() %>%
    # All balancings
    # All cat levels
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      num_col = "score",
      cat_col = "diagnosis",
      cat_levels = NULL,
      id_col = "participant",
      balance_size = TRUE,
      col_name = "n,i,s,cA"
    ) %>%
    # No IDs
    dplyr::ungroup() %>%
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      num_col = "score",
      cat_col = "diagnosis",
      cat_levels = NULL,
      balance_size = TRUE,
      col_name = "n,s,cA"
    ) %>%
    # No ID, size
    dplyr::ungroup() %>%
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      num_col = "score",
      cat_col = "diagnosis",
      cat_levels = ".majority",
      balance_size = TRUE,
      col_name = "n,c^"
    ) %>%
    # No ID, size, cat
    dplyr::ungroup() %>%
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      num_col = "score",
      balance_size = TRUE,
      col_name = "n,s"
    ) %>%
    # Num only
    dplyr::ungroup() %>%
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      num_col = "score",
      balance_size = FALSE,
      col_name = "n"
    ) %>%
    # size only
    dplyr::ungroup() %>%
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      balance_size = TRUE,
      col_name = "s"
    ) %>%
    # Cat only
    dplyr::ungroup() %>%
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      cat_col = "diagnosis",
      cat_levels = ".majority",
      balance_size = FALSE,
      col_name = "c^"
    ) %>%
    # Cat only all levels
    dplyr::ungroup() %>%
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      cat_col = "diagnosis",
      cat_levels = NULL,
      balance_size = FALSE,
      col_name = "cA"
    ) %>%
    # id only
    dplyr::ungroup() %>%
    collapse_groups(
      n = 4,
      group_cols = ".folds",
      id_col = "participant",
      balance_size = TRUE,
      col_name = "i"
    )

  new_group_cols <- setdiff(colnames(df_collapsed), colnames(df_folded))

  summ_bal <- summarize_balances(
    data = df_collapsed,
    group_cols = new_group_cols,
    num_cols = c("score"),
    cat_cols = "diagnosis",
    id_cols = "participant",
    include_normalized = TRUE
  )

  # n = numeric
  # c = categorical ; ^ = .majority; A = all levels
  # i = ID
  # s = size
  # R = Random collapsing (no balancing)
  # sampl = completely random
  summ_bal$Summary %>% ranked_balances()
  summ_bal$`Normalized Summary` %>% ranked_balances()


  # %>%
  #   dplyr::ungroup() %>%
  #   collapse_groups(
  #     n = 4,
  #     group_cols = ".folds",
  #     num_col = "age",
  #     cat_col = "diagnosis",
  #     cat_levels = NULL,
  #     col_name = ".cg2"
  #   ) %>%
  #   dplyr::ungroup() %>%
  #   collapse_groups(
  #     n = 4,
  #     group_cols = ".folds",
  #     num_col = "age",
  #     col_name = ".cg3"
  #   ) %>%
  #   dplyr::ungroup() %>%
  #   collapse_groups(
  #     n = 4,
  #     group_cols = ".folds",
  #     cat_col = "diagnosis",
  #     cat_levels = ".majority",
  #     col_name = ".cg4"
  #   ) %>%
  #   dplyr::ungroup() %>%
  #   collapse_groups(
  #     n = 4,
  #     group_cols = ".folds",
  #     col_name = ".cg5"
  #   ) %>%
  #   dplyr::ungroup()  %>%
  #   collapse_groups(
  #     n = 4,
  #     balance_size = FALSE,
  #     group_cols = ".folds",
  #     col_name = ".cg6"
  #   ) %>%
  #   dplyr::ungroup()

})

