library(groupdata2)
context("auto_tune_collapsings")


test_that("testing find_best_group_cols_()", {

  # Set seed
  xpectr::set_test_seed(42)

  # Create data frame
  df <- data.frame(
    "participant" = factor(rep(1:20, 3)),
    "age" = rep(sample(c(1:100), 20), 3),
    "diagnosis" = factor(rep(sample(c(1:3), 20, replace = TRUE), 3)),
    "score" = sample(c(1:100), 20 * 3)
  )
  df <- df %>% dplyr::arrange(participant)

  # Sample rows to get unequal sizes per participant
  df <- dplyr::sample_n(df, size = 27)

  # Create the initial groups (to be collapsed)
  df <- fold(
    data = df,
    k = 8,
    num_fold_cols = 5,
    method = "n_dist",
    id_col = "participant"
  )

  # Ungroup the data frame
  df <- dplyr::ungroup(df)

  best_cols <- find_best_group_cols_(
    data = df,
    num_new_group_cols = 3,
    group_cols_names = paste0(".folds_", 1:5),
    cat_cols = "diagnosis",
    num_cols = "age",
    id_cols = "participant",
    weights = c(
      "diagnosis" = 3,
      "age" = 5,
      "participant" = 2
    ),
    balance_size = TRUE
  )

  expect_equal(
    best_cols,
    c(".folds_4", ".folds_5", ".folds_1"),
    fixed = TRUE
  )

  # zero-variance
  df$.man_folds = 1

  best_cols <- find_best_group_cols_(
    data = df,
    num_new_group_cols = 2,
    group_cols_names = c(".folds_1", ".man_folds"),
    cat_cols = "diagnosis",
    num_cols = "age",
    id_cols = "participant",
    weights = c(
      "diagnosis" = 3,
      "age" = 5,
      "participant" = 2
    ),
    balance_size = TRUE
  )

  # .man_folds give NAs in ranked_balances
  # so it should rank last
  expect_equal(
    best_cols,
    c(".folds_1", ".man_folds")
  )

})

test_that("testing get_num_cols_to_create_()", {
  xpectr::set_test_seed(42)

  num_combi <- c(seq(from = 1, to = 30, by = 3))
  num_cols <- c(1, 4, 7, 18, 21, 49, 51, 74, 76)

  # Keep number of group cols constant
  # and get the different non-main combination multipliers
  num_non_main_combinations <- plyr::ldply(num_combi, function(nc) {
    get_num_cols_to_create_(num_combinations = nc,
                            num_new_group_cols = 3) %>%
      as.data.frame() %>%
      dplyr::mutate(num_combinations = nc)
  })

  # Keep number of combinations constant
  # and get the different numbers of main-combination
  # columns and random columns
  num_main_and_random_combinations <-
    plyr::ldply(num_cols, function(nc) {
      get_num_cols_to_create_(num_combinations = 6,
                              num_new_group_cols = nc) %>%
        as.data.frame() %>%
        dplyr::mutate(num_new_group_cols = nc)
    })


  ## Testing 'num_non_main_combinations'                                    ####
  ## Initially generated by xpectr
  xpectr::set_test_seed(42)
  # Testing class
  expect_equal(
    class(num_non_main_combinations),
    "data.frame",
    fixed = TRUE)
  # Testing column values
  expect_equal(
    num_non_main_combinations[["main"]],
    c(9, 9, 9, 9, 9, 9, 9, 9, 9, 9),
    tolerance = 1e-4)
  expect_equal(
    num_non_main_combinations[["non_main"]], # should be the only one depending on num_combinations
    c(4, 4, 3, 3, 2, 2, 2, 2, 2, 1),
    tolerance = 1e-4)
  expect_equal(
    num_non_main_combinations[["random"]],
    c(15, 15, 15, 15, 15, 15, 15, 15, 15, 15),
    tolerance = 1e-4)
  expect_equal(
    num_non_main_combinations[["num_combinations"]],
    c(1, 4, 7, 10, 13, 16, 19, 22, 25, 28),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(num_non_main_combinations),
    c("main", "non_main", "random", "num_combinations"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(num_non_main_combinations),
    c("numeric", "numeric", "numeric", "numeric"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(num_non_main_combinations),
    c("double", "double", "double", "double"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(num_non_main_combinations),
    c(10L, 4L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(num_non_main_combinations)),
    character(0),
    fixed = TRUE)
  ## Finished testing 'num_non_main_combinations'                           ####



  ## Testing 'num_main_and_random_combinations'                             ####
  ## Initially generated by xpectr
  xpectr::set_test_seed(42)
  # Assigning output
  output_19148 <- num_main_and_random_combinations
  # Testing class
  expect_equal(
    class(output_19148),
    "data.frame",
    fixed = TRUE)
  # Testing column values
  expect_equal(
    output_19148[["main"]],
    c(9, 9, 13, 33, 30, 69, 66, 89, 91),
    tolerance = 1e-4)
  expect_equal(
    output_19148[["non_main"]],
    c(3, 3, 3, 3, 3, 3, 3, 3, 3), # Should not depend on num_new_group_cols
    tolerance = 1e-4)
  expect_equal(
    output_19148[["random"]],
    c(15, 15, 15, 15, 30, 30, 40, 40, 38),
    tolerance = 1e-4)
  expect_equal(
    output_19148[["num_new_group_cols"]],
    c(1, 4, 7, 18, 21, 49, 51, 74, 76),
    tolerance = 1e-4)
  # Testing column names
  expect_equal(
    names(output_19148),
    c("main", "non_main", "random", "num_new_group_cols"),
    fixed = TRUE)
  # Testing column classes
  expect_equal(
    xpectr::element_classes(output_19148),
    c("numeric", "numeric", "numeric", "numeric"),
    fixed = TRUE)
  # Testing column types
  expect_equal(
    xpectr::element_types(output_19148),
    c("double", "double", "double", "double"),
    fixed = TRUE)
  # Testing dimensions
  expect_equal(
    dim(output_19148),
    c(9L, 4L))
  # Testing group keys
  expect_equal(
    colnames(dplyr::group_keys(output_19148)),
    character(0),
    fixed = TRUE)
  ## Finished testing 'num_main_and_random_combinations'                    ####


  ## Testing 'get_num_cols_to_create_(num_combinations = 0...'              ####
  ## Initially generated by xpectr
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_19148 <- xpectr::capture_side_effects(get_num_cols_to_create_(num_combinations = 0,
                            num_new_group_cols = 2), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19148[['error']]),
    xpectr::strip("Assertion on 'num_combinations' failed: Must be >= 1."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19148[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)
  ## Finished testing 'get_num_cols_to_create_(num_combinations = 0...'     ####


  ## Testing 'get_num_cols_to_create_(num_combinations = 2...'              ####
  ## Initially generated by xpectr
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_19148 <- xpectr::capture_side_effects(get_num_cols_to_create_(num_combinations = 2,
                            num_new_group_cols = 0), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19148[['error']]),
    xpectr::strip("Assertion on 'num_new_group_cols' failed: Must be >= 1."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19148[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)
  ## Finished testing 'get_num_cols_to_create_(num_combinations = 2...'     ####


  ## Testing 'get_num_cols_to_create_(num_combinations = 2...'              ####
  ## Initially generated by xpectr
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_19148 <- xpectr::capture_side_effects(get_num_cols_to_create_(num_combinations = 2,
                            num_new_group_cols = NA), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19148[['error']]),
    xpectr::strip("Assertion on 'num_new_group_cols' failed: May not be NA."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19148[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)
  ## Finished testing 'get_num_cols_to_create_(num_combinations = 2...'     ####


  ## Testing 'get_num_cols_to_create_(num_combinations = N...'              ####
  ## Initially generated by xpectr
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_19148 <- xpectr::capture_side_effects(get_num_cols_to_create_(num_combinations = NA,
                            num_new_group_cols = 2), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19148[['error']]),
    xpectr::strip("Assertion on 'num_combinations' failed: May not be NA."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19148[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)
  ## Finished testing 'get_num_cols_to_create_(num_combinations = N...'     ####

})

test_that("testing inform_user_about_autotune_()", {

  ## Testing 'inform_user_about_autotune_( num_cols_to_cre...'              ####
  ## Initially generated by xpectr
  xpectr::set_test_seed(42)
  # Assigning output
  output_19148 <- inform_user_about_autotune_(
      num_cols_to_create_settings = list(
        "main" = 61,
        "non_main" = 2,
        "random" = 7
      ),
      num_combinations = 15,
      num_new_group_cols = 7,
      all_balance_cols = c("a", "b", "c"),
      parallel = FALSE,
      unique_new_group_cols_only = TRUE,
      return_string = TRUE
    )
  # Testing class
  expect_equal(
    class(output_19148),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_19148,
    type = "character")
  # Testing values
  expect_equal(
    output_19148,
    paste0("-----------------------------------------------------------",
           "-\n  `collapse_groups()` auto-tuning\n----------------------",
           "--------------------------------------\n  Finding 7 unique g",
           "roup collapsings that best balance:\n    a, b, c\n  Will att",
           "empt to create:\n    Extreme pairing balanced splits: 87\n  ",
           "  Extreme triplets balanced splits: 33\n    Random splits: 7",
           "\n    Total number of grouping columns: 127\n---------------",
           "---------------------------------------------\n  Consider en",
           "abling parallelization. See ?collapse_groups\n--------------",
           "----------------------------------------------\n"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_19148),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_19148),
    1L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_19148)),
    1L)
  ## Finished testing 'inform_user_about_autotune_( num_cols_to_cre...'     ####


  ## Testing 'inform_user_about_autotune_( num_cols_to_cre...'              ####
  ## Initially generated by xpectr
  xpectr::set_test_seed(42)
  # Assigning output
  output_19148 <- inform_user_about_autotune_(
      num_cols_to_create_settings = list(
        "main" = 61,
        "non_main" = 2,
        "random" = 7
      ),
      num_combinations = 15,
      num_new_group_cols = 7,
      all_balance_cols = c("a", "b", "c"),
      parallel = TRUE,
      unique_new_group_cols_only = FALSE,
      return_string = TRUE
    )
  # Testing class
  expect_equal(
    class(output_19148),
    "character",
    fixed = TRUE)
  # Testing type
  expect_type(
    output_19148,
    type = "character")
  # Testing values
  expect_equal(
    output_19148,
    paste0("-----------------------------------------------------------",
           "-\n  `collapse_groups()` auto-tuning\n----------------------",
           "--------------------------------------\n  Finding 7 group co",
           "llapsings that best balance:\n    a, b, c\n  Will attempt to",
           " create:\n    Extreme pairing balanced splits: 87\n    Extre",
           "me triplets balanced splits: 33\n    Random splits: 7\n    T",
           "otal number of grouping columns: 127\n----------------------",
           "--------------------------------------\n"),
    fixed = TRUE)
  # Testing names
  expect_equal(
    names(output_19148),
    NULL,
    fixed = TRUE)
  # Testing length
  expect_equal(
    length(output_19148),
    1L)
  # Testing sum of element lengths
  expect_equal(
    sum(xpectr::element_lengths(output_19148)),
    1L)
  ## Finished testing 'inform_user_about_autotune_( num_cols_to_cre...'     ####


  ## Testing 'inform_user_about_autotune_( num_cols_to_cre...'              ####
  ## Initially generated by xpectr
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_19148 <- xpectr::capture_side_effects(inform_user_about_autotune_(
      num_cols_to_create_settings = list(
        "main" = 61,
        "non_main" = 2,
        "random" = 7
      ),
      num_combinations = 15,
      num_new_group_cols = 7,
      all_balance_cols = c("a", NA, "c"),
      parallel = TRUE,
      unique_new_group_cols_only = FALSE,
      return_string = TRUE
    ), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19148[['error']]),
    xpectr::strip("Assertion on 'all_balance_cols' failed: Contains missing values (element 2)."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19148[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)
  ## Finished testing 'inform_user_about_autotune_( num_cols_to_cre...'     ####


  ## Testing 'inform_user_about_autotune_( num_cols_to_cre...'              ####
  ## Initially generated by xpectr
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_19148 <- xpectr::capture_side_effects(inform_user_about_autotune_(
      num_cols_to_create_settings = list(
        "main" = NA,
        "non_main" = 2,
        "random" = 7
      ),
      num_combinations = 15,
      num_new_group_cols = 7,
      all_balance_cols = c("a", "c"),
      parallel = TRUE,
      unique_new_group_cols_only = FALSE,
      return_string = TRUE
    ), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19148[['error']]),
    xpectr::strip("Assertion on 'num_cols_to_create_settings[['main']]' failed: May not be NA."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19148[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)
  ## Finished testing 'inform_user_about_autotune_( num_cols_to_cre...'     ####


  ## Testing 'inform_user_about_autotune_( num_cols_to_cre...'              ####
  ## Initially generated by xpectr
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_19148 <- xpectr::capture_side_effects(inform_user_about_autotune_(
      num_cols_to_create_settings = list(
        "main" = 61,
        "non_main" = 2,
        "random" = 7
      ),
      num_combinations = NA,
      num_new_group_cols = 7,
      all_balance_cols = c("a", "c"),
      parallel = TRUE,
      unique_new_group_cols_only = FALSE,
      return_string = TRUE
    ), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19148[['error']]),
    xpectr::strip("Assertion on 'num_combinations' failed: May not be NA."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19148[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)
  ## Finished testing 'inform_user_about_autotune_( num_cols_to_cre...'     ####


  ## Testing 'inform_user_about_autotune_( num_cols_to_cre...'              ####
  ## Initially generated by xpectr
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_19148 <- xpectr::capture_side_effects(inform_user_about_autotune_(
      num_cols_to_create_settings = list(
        "main" = 61,
        "non_main" = 2,
        "random" = 7
      ),
      num_combinations = 15,
      num_new_group_cols = NA,
      all_balance_cols = c("a", "c"),
      parallel = TRUE,
      unique_new_group_cols_only = FALSE,
      return_string = TRUE
    ), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19148[['error']]),
    xpectr::strip("Assertion on 'num_new_group_cols' failed: May not be NA."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19148[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)
  ## Finished testing 'inform_user_about_autotune_( num_cols_to_cre...'     ####


  ## Testing 'inform_user_about_autotune_( num_cols_to_cre...'              ####
  ## Initially generated by xpectr
  xpectr::set_test_seed(42)
  # Testing side effects
  # Assigning side effects
  side_effects_19148 <- xpectr::capture_side_effects(inform_user_about_autotune_(
      num_cols_to_create_settings = list(
        "main" = 22,
        "non_main" = 2,
        "random" = 7
      ),
      num_combinations = 15,
      num_new_group_cols = 7,
      all_balance_cols = c("a", "c"),
      parallel = TRUE,
      unique_new_group_cols_only = FALSE,
      return_string = NA
    ), reset_seed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19148[['error']]),
    xpectr::strip("Assertion on 'return_string' failed: May not be NA."),
    fixed = TRUE)
  expect_equal(
    xpectr::strip(side_effects_19148[['error_class']]),
    xpectr::strip(c("simpleError", "error", "condition")),
    fixed = TRUE)
  ## Finished testing 'inform_user_about_autotune_( num_cols_to_cre...'     ####


})
